[package]
authors = ["Peter Allin <peter@peca.dk>"]
edition = "2018"
name = "web-calc"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
yew = "0.17"

[dev-dependencies]
assert_approx_eq = "1.1"
matches = "0.1"
